imports and api

In [39]:
from comment_extraction import api_setup, extract_comments
from comment_class import RawComment
from mongo_code import mongo_connect, get_collection, insert_comments, convert_df_to_list, load_collection_to_df
from comment_preprocessing import preprocess_df

In [38]:
import importlib, comment_preprocessing
importlib.reload(comment_preprocessing)

general functions for setup

In [42]:
youtube_api = api_setup()
client = mongo_connect()
comments_db = client["comments_db"]
raw_comments = get_collection(comments_db, "raw_comments")
preprocessed_comments = get_collection(comments_db, "preprocssed_comments")

loaded youtube api
connected to mongodb at mongodb://localhost:27017/

In [5]:
youtube_api = api_setup()
video = "Y8yTY_7w3KA"

df1 = extract_comments(youtube_api,video)

df1.head()

loaded youtube api
Video Y8yTY_7w3KA: collected 129 rows so far
Video Y8yTY_7w3KA: collected 256 rows so far
Video Y8yTY_7w3KA: collected 502 rows so far
Video Y8yTY_7w3KA: collected 823 rows so far
Video Y8yTY_7w3KA: collected 1037 rows so far

,comment_id,video_id,parent_id,is_reply,author,text,like_count,public
0,UgzjI6TjvTQiaNdFJDh4AaABAg,Y8yTY_7w3KA,NaN,False,@autogefuehl,Note that contrary to the first info and contr...,57,True
1,UgzjI6TjvTQiaNdFJDh4AaABAg.9voUleYQpWB9vp-UsnhkGH,Y8yTY_7w3KA,UgzjI6TjvTQiaNdFJDh4AaABAg,True,@Rokii92,"you mean ""horror sound""? :D",0,True
2,UgzjI6TjvTQiaNdFJDh4AaABAg.9voUleYQpWB9vpI9k1jApB,Y8yTY_7w3KA,UgzjI6TjvTQiaNdFJDh4AaABAg,True,@Elaba_,Tammy AI is without a job now.,0,True
3,UgzjI6TjvTQiaNdFJDh4AaABAg.9voUleYQpWB9vytQZ977iX,Y8yTY_7w3KA,UgzjI6TjvTQiaNdFJDh4AaABAg,True,@whatnow9653,"1:29 lolly pops, cherry pies, cream puffs...",0,True
4,UgzjI6TjvTQiaNdFJDh4AaABAg.9voUleYQpWB9wBY-12Xroy,Y8yTY_7w3KA,UgzjI6TjvTQiaNdFJDh4AaABAg,True,@rondhole,What separate a good and bad BEV is the heat m...,0,True

In [ ]:
raw_comments_list = convert_df_to_list(df1)
inserted_comments = insert_comments(raw_comments, raw_comments_list)

connected to mongodb at mongodb://localhost:27017/
inserted 1031 new comment(s)

In [ ]:
df1 = load_collection_to_df(raw_comments)
df_clean = preprocess_df(df1)

loaded 1031 documents from raw_comments
Final number of comments after cleaning: 959
Comments removed: 72

In [ ]:
preprocssed_comments_list = convert_df_to_list(df_clean)
inserted_comments = insert_comments(preprocessed_comments, preprocssed_comments_list)

,text,clean_text
0,Note that contrary to the first info and contr...,Note that contrary to the first info and contr...
1,"you mean ""horror sound""? :D","you mean ""horror sound""? :D"
2,Tammy AI is without a job now.,Tammy AI is without a job now.
3,"1:29 lolly pops, cherry pies, cream puffs...","1:29 lolly pops, cherry pies, cream puffs, ice..."
4,What separate a good and bad BEV is the heat m...,What separate a good and bad BEV is the heat m...
5,I take it from your review that the Seal drive...,I take it from your review that the Seal drive...
6,I could build cheap cars if I used slave labour,I could build cheap cars if I used slave labour
7,Do the internal cameras and mics constantly re...,Do the internal cameras and mics constantly re...
8,"Europe also was a lot of money, but we prefer ...","Europe also was a lot of money, but we prefer ..."
9,BYD is like the Kia lmao..its not all that one...,BYD is like the Kia lmao..its not all that one...