In [14]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
from modules.data_store import save_df_csv, load_df_csv, save_transcript, load_transcript, transcript_exists
from modules.retrieval import build_faiss, load_faiss, load_corpus_from_df
from modules.pipelines import *
from modules.embeddings import embedding_setup
from modules.processing import spacy_setup
from modules.transcript_extraction import nltk_setup
from modules.comment_extraction import api_setup

import pandas as pd

In [12]:
nltk_setup()
video = 'Y8yTY_7w3KA'
nlp = spacy_setup()
embedding = embedding_setup()
youtube_api = api_setup()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Abdallah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Abdallah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Abdallah\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Abdallah\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

nltk packages downloaded
loaded youtube api

In [16]:
comments_1_df = extract_video_comments_full(video,youtube_api,nlp, embedding)
comments_1_df.head()

Video Y8yTY_7w3KA: collected 129 rows so far
Video Y8yTY_7w3KA: collected 256 rows so far
extracted 256 comments
save Y8yTY_7w3KA_raw of 256 cols  to model_data\Y8yTY_7w3KA_raw
Final number of comments after cleaning: 240
Comments removed: 16
TF-IDF matrix shape: (240, 280)
processed 240 comments

,source_id,source_type,video_id,parent_id,is_reply,author,text,like_count,public,clean_text,entities,sentiment_score,sentiment,keywords,embedding
0,UgzjI6TjvTQiaNdFJDh4AaABAg,comment,Y8yTY_7w3KA,NaN,False,@autogefuehl,Note that contrary to the first info and contr...,57,True,Note that contrary to the first info and contr...,"[BYD, Germany, 02:35 Sporty, RWD, AWD, 04:19 S...",0.8442,Positive,"[byd, comfort, contrary, 29, steering]","[-0.049880978, -0.009711982, 0.06287992, 0.010..."
1,UgzjI6TjvTQiaNdFJDh4AaABAg.9voUleYQpWB9vp-UsnhkGH,comment,Y8yTY_7w3KA,UgzjI6TjvTQiaNdFJDh4AaABAg,True,@Rokii92,"you mean ""horror sound""? :D",0,True,"you mean ""horror sound""? :D",[],0.0857,Positive,"[mean, sound]","[-0.120427154, 0.0056267357, 0.007439199, -0.0..."
2,UgzjI6TjvTQiaNdFJDh4AaABAg.9voUleYQpWB9vpI9k1jApB,comment,Y8yTY_7w3KA,UgzjI6TjvTQiaNdFJDh4AaABAg,True,@Elaba_,Tammy AI is without a job now.,0,True,Tammy AI is without a job now.,[Tammy AI],0.0000,Neutral,[],"[-0.15995634, -0.014780474, 0.06653771, -0.014..."
3,UgzjI6TjvTQiaNdFJDh4AaABAg.9voUleYQpWB9vytQZ977iX,comment,Y8yTY_7w3KA,UgzjI6TjvTQiaNdFJDh4AaABAg,True,@whatnow9653,"1:29 lolly pops, cherry pies, cream puffs...",0,True,"1:29 lolly pops, cherry pies, cream puffs, ice...",[],0.5106,Positive,"[cream, 29, ice cream, ice, free]","[-0.09148398, 0.010680194, 0.031913865, 0.0315..."
4,UgzjI6TjvTQiaNdFJDh4AaABAg.9voUleYQpWB9wBY-12Xroy,comment,Y8yTY_7w3KA,UgzjI6TjvTQiaNdFJDh4AaABAg,True,@rondhole,What separate a good and bad BEV is the heat m...,0,True,What separate a good and bad BEV is the heat m...,"[Octovalve, Tesla]",0.4404,Positive,"[tesla, bad, market, compared, long]","[-0.081726454, -0.014096241, 0.012966923, 0.00..."

In [17]:
video2 = 'V0wtNI-rzSg'
comments_2_df = extract_video_comments_full(video2,youtube_api,nlp, embedding)
comments_2_df.head()

Video V0wtNI-rzSg: collected 100 rows so far
Video V0wtNI-rzSg: collected 202 rows so far
extracted 202 comments
save V0wtNI-rzSg_raw of 202 cols  to model_data\V0wtNI-rzSg_raw
Final number of comments after cleaning: 178
Comments removed: 24
TF-IDF matrix shape: (178, 98)
processed 178 comments

,source_id,source_type,video_id,parent_id,is_reply,author,text,like_count,public,clean_text,entities,sentiment_score,sentiment,keywords,embedding
0,UgyEF1U2INCc0EZxf_t4AaABAg,comment,V0wtNI-rzSg,NaN,False,@geoffwalker7530,"Note the crap door handles, sale killer straig...",0,True,"Note the crap door handles, sale killer straig...",[],-0.7184,Negative,[crap],"[-0.13544238, -0.038832527, 0.042742647, 0.017..."
1,Ugz5s0PKBupBXK4Ugld4AaABAg,comment,V0wtNI-rzSg,NaN,False,@marceln3107,"*In the MY2026, BYD dismissed this feature.",0,True,"*In the MY2026, BYD dismissed this feature.","[MY2026, BYD]",0.0000,Neutral,"[feature, byd]","[-0.13474578, -0.022500524, 0.045074645, -0.00..."
2,UgyqNGNLVqXddAdC5Wx4AaABAg,comment,V0wtNI-rzSg,NaN,False,@carlkirk3467,Even better if there were no touchscreens to d...,0,True,Even better if there were no touchscreens to d...,[],-0.1280,Negative,"[driver, better]","[-0.11380915, -0.039813634, 0.050478853, 0.047..."
3,Ugx9DGiRIsGm3DsEPgt4AaABAg,comment,V0wtNI-rzSg,NaN,False,@nobodyshero200,So interesting you chose an EV as a daily. Tha...,0,True,So interesting you chose an EV as a daily. Tha...,[],-0.1298,Negative,"[interesting, daily, ev, really, cars]","[-0.13519152, -0.0036311098, 0.06373591, 0.010..."
4,UgyaUiiMq4imxJQceZB4AaABAg,comment,V0wtNI-rzSg,NaN,False,@williamwildcat,I don’t care how nice it is it’s a stupid ev,0,True,I don’t care how nice it is it’s a stupid ev,[],0.3818,Positive,"[nice, stupid, ev, don]","[-0.16873242, -0.041292094, 0.059854172, 0.029..."

In [20]:
transcript_1_df = extract_video_transcript_full(video,nlp,embedding,win=60)
transcript_2_df = extract_video_transcript_full(video2,nlp,embedding,win=60)

saved 358 segments -> model_data\Y8yTY_7w3KA.json
transcript does not exist, saving raw transcript
Y8yTY_7w3KA: 22 chunks
processed transcript for Y8yTY_7w3KA of 22
saved 27 segments -> model_data\V0wtNI-rzSg.json
transcript does not exist, saving raw transcript
V0wtNI-rzSg: 1 chunks
processed transcript for V0wtNI-rzSg of 1

In [21]:
all_dfs = []
all_dfs.append(comments_1_df)
all_dfs.append(comments_2_df)
all_dfs.append(transcript_1_df)
all_dfs.append(transcript_2_df)
meta_df = pd.concat(all_dfs, ignore_index=True)
print(len(meta_df), "total rows")
print(meta_df["source_type"].value_counts())
print(meta_df["video_id"].value_counts())

441 total rows
source_type
comment       418
transcript     23
Name: count, dtype: int64
video_id
Y8yTY_7w3KA    262
V0wtNI-rzSg    179
Name: count, dtype: int64

In [ ]:
save_df_csv(meta_df,f'meta_df.csv',True)