In [10]:
%load_ext autoreload
%autoreload 2

In [11]:
from modules.transcript_extraction import *
# from mongo_code import *
from modules.processing import extract_entities_df, spacy_setup
from modules.embeddings import embedding_setup, embed_df
from modules.retrieval import *
from modules.data_store import *

In [8]:
nltk_setup()
video = 'Y8yTY_7w3KA'
# client = mongo_connect()
# meta_db = client['metadata_db']
# meta_data = get_collection(meta_db,"meta_data")
nlp = spacy_setup()
embedding = embedding_setup()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Abdallah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Abdallah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Abdallah\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Abdallah\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

nltk packages downloaded

In [14]:
# transcript_lines = parse_transcript(video)
# save_transcript(video, transcript_lines)

transcript_lines = load_transcript(video)

loaded 358 segments from model_data\Y8yTY_7w3KA.json

In [15]:
df1 = extract_transcript(video,60)
df1.head()

Y8yTY_7w3KA: 22 chunks

,source_id,source_type,video_id,chunk_index,start_time,text,noun_phrases
0,Y8yTY_7w3KA_t_0,transcript,Y8yTY_7w3KA,0,0.1,"Tesla is the biggest EV manufacturer, BYD says...","[Tesla, EV manufacturer, BYD, beer, Europe, Ge..."
1,Y8yTY_7w3KA_t_1,transcript,Y8yTY_7w3KA,1,62.7,"drive version called Excellence, there's also ...","[drive version, Excellence, variable frequency..."
2,Y8yTY_7w3KA_t_2,transcript,Y8yTY_7w3KA,2,125.5,"battery, 82.5 kilowatt hours net, and it's an ...","[battery, kilowatt hours, an LFP battery, exam..."
3,Y8yTY_7w3KA_t_3,transcript,Y8yTY_7w3KA,3,190.7,"housing itself, and that is actually something...","[housing, something, the stability, the whole ..."
4,Y8yTY_7w3KA_t_4,transcript,Y8yTY_7w3KA,4,253.4,"and we can see it has digital instruments, yes...","[digital instruments, microfiber inserts, thes..."

In [16]:
processed_df = extract_entities_df(df1, nlp, 'text')
processed_df.head(20)

,source_id,source_type,video_id,chunk_index,start_time,text,noun_phrases,entities
0,Y8yTY_7w3KA_t_0,transcript,Y8yTY_7w3KA,0,0.1,"Tesla is the biggest EV manufacturer, BYD says...","[Tesla, EV manufacturer, BYD, beer, Europe, Ge...","[Tesla, BYD, Europe, Germany, Model 3, Thomas]"
1,Y8yTY_7w3KA_t_1,transcript,Y8yTY_7w3KA,1,62.7,"drive version called Excellence, there's also ...","[drive version, Excellence, variable frequency...","[Excellence, BYD]"
2,Y8yTY_7w3KA_t_2,transcript,Y8yTY_7w3KA,2,125.5,"battery, 82.5 kilowatt hours net, and it's an ...","[battery, kilowatt hours, an LFP battery, exam...","[LFP, Model 3]"
3,Y8yTY_7w3KA_t_3,transcript,Y8yTY_7w3KA,3,190.7,"housing itself, and that is actually something...","[housing, something, the stability, the whole ...",[]
4,Y8yTY_7w3KA_t_4,transcript,Y8yTY_7w3KA,4,253.4,"and we can see it has digital instruments, yes...","[digital instruments, microfiber inserts, thes...","[BYD, Europe, Germany]"
5,Y8yTY_7w3KA_t_5,transcript,Y8yTY_7w3KA,5,316.2,"have them, that's a pro in comparison to the T...","[comparison, the Tesla Model, 15.6-inch screen...","[Model 3, Digital]"
6,Y8yTY_7w3KA_t_6,transcript,Y8yTY_7w3KA,6,378.1,"And, also important, they do offer Apple CarPl...","[Apple CarPlay, Android Auto, large integratio...","[Apple CarPlay, Android Auto, NFC]"
7,Y8yTY_7w3KA_t_7,transcript,Y8yTY_7w3KA,7,439.4,"Inside of the rear doors, also the nice microf...","[the rear doors, the nice microfiber insert, h...",[]
8,Y8yTY_7w3KA_t_8,transcript,Y8yTY_7w3KA,8,501.6,This one you can fold down. Adaptive cup holde...,"[Adaptive cup holders, everything feels, the w...","[Mercedes, Model 3]"
9,Y8yTY_7w3KA_t_9,transcript,Y8yTY_7w3KA,9,566.1,"know, like this emergency kit and so on, and f...","[this emergency kit, anything, the rear seats,...",[Thomas]
10,Y8yTY_7w3KA_t_10,transcript,Y8yTY_7w3KA,10,626.5,"It's actually for pedestrians, but you hear it...","[pedestrians, the inside, a little bit, the mo...",[]
11,Y8yTY_7w3KA_t_11,transcript,Y8yTY_7w3KA,11,688.4,"here, the steering feel, you don't have any de...","[feel, any dead zone area, the outside, good p...",[]
12,Y8yTY_7w3KA_t_12,transcript,Y8yTY_7w3KA,12,750.0,I wouldn't say it's a one-pedal driving feelin...,"[a one-pedal driving feeling, digital instrume...",[Model 3]
13,Y8yTY_7w3KA_t_13,transcript,Y8yTY_7w3KA,13,812.3,"Then, here, the road gets a little bit rougher...","[the road, a little bit, 19-inch wheels, the a...","[the Model 3, Model Y. Let's, the German Autob..."
14,Y8yTY_7w3KA_t_14,transcript,Y8yTY_7w3KA,14,873.9,Something. And here we are at about 50 kilomet...,"[kilometers, an hour, Plop, the speedometer, t...","[Leah, C63, Germany]"
15,Y8yTY_7w3KA_t_15,transcript,Y8yTY_7w3KA,15,938.3,this one here is a couple of thousand euros mo...,"[a couple, thousand euros, the Tesla Model, th...","[Model 3, Tesla Model 3, Tesla, Mercedes]"
16,Y8yTY_7w3KA_t_16,transcript,Y8yTY_7w3KA,16,1000.4,"ticks all the boxes, you know, in that corner,...","[ticks, the boxes, that corner, good feeling, ...","[European, Chinese]"
17,Y8yTY_7w3KA_t_17,transcript,Y8yTY_7w3KA,17,1060.8,We are in this dark mode here now for the scre...,"[this dark mode, the screens, the auto mode, t...",[Autobahn]
18,Y8yTY_7w3KA_t_18,transcript,Y8yTY_7w3KA,18,1123.1,"So, hmm. Did I find out something here? Well, ...","[hmm, Did, something, Well, the German Autobah...",[the German Autobahn]
19,Y8yTY_7w3KA_t_19,transcript,Y8yTY_7w3KA,19,1184.3,"So, what else did I realize while driving? The...","[The ACC, five-kilometer steps, course, the as...","[ACC, Zeeks, Xpeng, Tang, European, Interior, ..."

In [17]:
df1_emb = embed_df(df1, embedding, 'text')
df1_emb.head()

,source_id,source_type,video_id,chunk_index,start_time,text,noun_phrases,embedding
0,Y8yTY_7w3KA_t_0,transcript,Y8yTY_7w3KA,0,0.1,"Tesla is the biggest EV manufacturer, BYD says...","[Tesla, EV manufacturer, BYD, beer, Europe, Ge...","[-0.05558837, -0.039070785, 0.023531472, 0.019..."
1,Y8yTY_7w3KA_t_1,transcript,Y8yTY_7w3KA,1,62.7,"drive version called Excellence, there's also ...","[drive version, Excellence, variable frequency...","[-0.04662706, -0.06687245, 0.023861948, 0.0249..."
2,Y8yTY_7w3KA_t_2,transcript,Y8yTY_7w3KA,2,125.5,"battery, 82.5 kilowatt hours net, and it's an ...","[battery, kilowatt hours, an LFP battery, exam...","[0.0016122252, -0.061130617, 0.017116798, 0.03..."
3,Y8yTY_7w3KA_t_3,transcript,Y8yTY_7w3KA,3,190.7,"housing itself, and that is actually something...","[housing, something, the stability, the whole ...","[-0.045709502, -0.038277645, -0.01687789, -0.0..."
4,Y8yTY_7w3KA_t_4,transcript,Y8yTY_7w3KA,4,253.4,"and we can see it has digital instruments, yes...","[digital instruments, microfiber inserts, thes...","[-0.033574592, -0.008058413, 0.03460888, 0.001..."

In [18]:
print("embedding" in df1_emb.columns)        # should be True
print(len(df1_emb.iloc[0]["embedding"]))      # should be 768
print(df1_emb.iloc[0]["embedding"][:5])

True
768
[-0.05558837, -0.039070785, 0.023531472, 0.019439068, 0.04525841]

In [19]:
save_df_csv(df1_emb,f'{video}_metadata')

save Y8yTY_7w3KA_metadata of 22 cols  to model_data\Y8yTY_7w3KA_metadata

In [ ]:
texts, vectors, metadata = load_corpus_from_df(df1_emb)
vs = build_faiss(texts, vectors, metadata, embedding)

results = semantic_search(vs, "is tesla better or byd is better?", k=5)
for r in results:
    print(r["source_type"], "|", r["text"][:80])

loaded 143 doc from collection Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, server_api=<pymongo.server_api.ServerApi object at 0x000001BA680D9C10>), 'metadata_db'), 'meta_data')
built + saved FAISS index (143 vectors) -> faiss_store
comment | Only a crazy person would pick a BYD instead of a Tesla. All other EV companies
comment | which color the best for byd seal, Aurora White or Atlantis Grey ?
comment | Will you also review BYD Han?
comment | Clearly a premium product cannot be compared with the tesla model 3 in my opinio
comment | If you had to pick between this and volvo ex30 dual motor ultra, which one would